In [4]:
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
import time
from bs4 import BeautifulSoup
import requests
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

In [57]:
driver = webdriver.Chrome("E:\chromedriver_win32\chromedriver.exe")

In [58]:
driver.get('https://www.yatra.com/')

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=23%2F03%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-home&unqvaldesktop=193853671637'
driver.get(url)

In [ ]:
Company_Name = []
jt = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt:
    j =data.text
    Company_Name.append(j)
Company_Name

In [ ]:
len(Company_Name)

In [ ]:
Flight_Name = []
fn = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn:
    f = data.text
    Flight_Name.append(f)
Flight_Name

In [ ]:
Arrival = []
ar = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar:
    a = data.text
    Arrival.append(a)
Arrival

In [ ]:
Departure = []
dr = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr:
    d = data.text.split('\n')[2]
    Departure.append(d)
Departure

In [ ]:
Source = []
sr = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr:
    s = data.text.split('\n')[1]
    Source.append(s)
Source

In [ ]:
Destination = []
dn = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn:
    ds = data.text.split('\n')[-1]
    Destination.append(ds)
Destination

In [ ]:
Duration = []
dr = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr:
    d = data.text
    Duration.append(d)
Duration

In [ ]:
Stops = []
st = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st:
    s = data.text.split('\n')[1]
    Stops.append(s)
Stops

In [ ]:
Meals = []
ms = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms:
    m = data.text
    Meals.append(m)
Meals

In [ ]:
len(Meals)

In [ ]:
Price = []
pr = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr:
    p = data.text
    Price.append(p)
Price

In [ ]:
yt = {'Company_Name': Company_Name,'Flight_Name':Flight_Name,'Arrival':Arrival,'Departure':Departure,'Source':Source,'Destination':Destination,'Duration':Duration,'Stops': Stops,'Meals_Avilablity':Meals,'Price':Price}
df1 = pd.DataFrame.from_dict(yt,orient = 'index')
df1 = df1.transpose()
df1

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1177705634423&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name1 = []
jt1 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt1:
    j1 =data.text
    Company_Name1.append(j1)
Company_Name1

In [ ]:
Flight_Name1 = []
fn1 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn1:
    f1 = data.text
    Flight_Name1.append(f1)
Flight_Name1

In [ ]:
Arrival1 = []
ar1 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar1:
    a1 = data.text
    Arrival1.append(a1)
Arrival1

In [ ]:
Departure1 = []
dr1 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr1:
    d1 = data.text.split('\n')[2]
    Departure1.append(d1)
Departure1

In [ ]:
Source1 = []
sr1 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr1:
    s1 = data.text.split('\n')[1]
    Source1.append(s1)
Source1

In [ ]:
Destination1 = []
dn1 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn1:
    ds1 = data.text.split('\n')[-1]
    Destination1.append(ds1)
Destination1

In [ ]:
Duration1 = []
dr1 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr1:
    d1 = data.text
    Duration1.append(d1)
Duration1

In [ ]:
Stops1 = []
st1 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st1:
    s1 = data.text.split('\n')[1]
    Stops1.append(s1)
Stops1

In [ ]:
Meals1 = []
ms1 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms1:
    m1 = data.text
    Meals1.append(m1)
Meals1

In [ ]:
Price1 = []
pr1 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr1:
    p1 = data.text
    Price1.append(p1)
Price1

In [ ]:
yt1 = {'Company_Name': Company_Name1,'Flight_Name':Flight_Name1,'Arrival':Arrival1,'Departure':Departure1,'Source':Source1,'Destination':Destination1,'Duration':Duration1,'Stops': Stops1,'Meals_Avilablity':Meals1,'Price':Price1}
df2 = pd.DataFrame.from_dict(yt1,orient = 'index')
df2 = df2.transpose()
df2

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=1501235578689&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name2 = []
jt2 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt2:
    j2 =data.text
    Company_Name2.append(j2)
Company_Name2

In [ ]:
Flight_Name2 = []
fn2 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn2:
    f2 = data.text
    Flight_Name2.append(f2)
Flight_Name2

In [ ]:
Arrival2 = []
ar2 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar2:
    a2 = data.text
    Arrival2.append(a2)
Arrival2

In [ ]:
Departure2 = []
dr2 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr2:
    d2 = data.text.split('\n')[2]
    Departure2.append(d2)
Departure2

In [ ]:
Source2 = []
sr2 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr2:
    s2 = data.text.split('\n')[1]
    Source2.append(s2)
Source2

In [ ]:
Destination2 = []
dn2 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn2:
    ds2 = data.text.split('\n')[-1]
    Destination2.append(ds2)
Destination2

In [ ]:
Duration2 = []
dr2 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr2:
    d2 = data.text
    Duration2.append(d2)
Duration2

In [ ]:
Stops2 = []
st2 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st2:
    s2 = data.text.split('\n')[1]
    Stops2.append(s2)
Stops2

In [ ]:
Meals2 = []
ms2 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms2:
    m2 = data.text
    Meals2.append(m2)
Meals2

In [ ]:
Price2 = []
pr2 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr2:
    p2 = data.text
    Price2.append(p2)
Price2

In [ ]:
yt2 = {'Company_Name': Company_Name2,'Flight_Name':Flight_Name2,'Arrival':Arrival2,'Departure':Departure2,'Source':Source2,'Destination':Destination2,'Duration':Duration2,'Stops': Stops2,'Meals_Avilablity':Meals2,'Price':Price2}
df3 = pd.DataFrame.from_dict(yt2,orient = 'index')
df3 = df3.transpose()
df3

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=23%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=169249450326&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name3 = []
jt3 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt3:
    j3 =data.text
    Company_Name3.append(j3)
Company_Name3

In [ ]:
Flight_Name3 = []
fn3 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn3:
    f3 = data.text
    Flight_Name3.append(f3)
Flight_Name3

In [ ]:
Arrival3 = []
ar3 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar3:
    a3 = data.text
    Arrival3.append(a3)
Arrival3

In [ ]:
Departure3 = []
dr3 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr3:
    d3 = data.text.split('\n')[2]
    Departure3.append(d3)
Departure3

In [ ]:
Source3 = []
sr3 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr3:
    s3 = data.text.split('\n')[1]
    Source3.append(s3)
Source3

In [ ]:
Destination3 = []
dn3 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn3:
    ds3 = data.text.split('\n')[-1]
    Destination3.append(ds3)
Destination3

In [ ]:
Duration3 = []
dr3 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr3:
    d3 = data.text
    Duration3.append(d3)
Duration3

In [ ]:
Stops3 = []
st3 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st3:
    s3 = data.text.split('\n')[1]
    Stops3.append(s3)
Stops3

In [ ]:
Meals3 = []
ms3 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms3:
    m3 = data.text
    Meals3.append(m3)
Meals3

In [ ]:
Price3 = []
pr3 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr3:
    p3 = data.text
    Price3.append(p3)
Price3

In [ ]:
yt3 = {'Company_Name': Company_Name3,'Flight_Name':Flight_Name3,'Arrival':Arrival3,'Departure':Departure3,'Source':Source3,'Destination':Destination3,'Duration':Duration3,'Stops': Stops3,'Meals_Avilablity':Meals3,'Price':Price3}
df4 = pd.DataFrame.from_dict(yt3,orient = 'index')
df4 = df4.transpose()
df4

In [ ]:
df = pd.concat([df1,df2,df3,df4])
df

In [ ]:
df.to_csv("E:\Data set\Flightprice1.csv")

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=24%2F03%2F2022&hb=0&noOfSegments=1&origin=HYD&originCountry=IN&type=O&unique=1595831431122&version=1.3&viewName=normal'
driver.get(url)

In [ ]:
Company_Name4 = []
jt4 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt4:
    j4 =data.text
    Company_Name4.append(j4)
Company_Name4

In [ ]:
Flight_Name4 = []
fn4 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn4:
    f4 = data.text
    Flight_Name4.append(f4)
Flight_Name4

In [ ]:
Arrival4 = []
ar4 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar4:
    a4 = data.text
    Arrival4.append(a4)
Arrival4

In [ ]:
Departure4 = []
dr4 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr4:
    d4 = data.text.split('\n')[2]
    Departure4.append(d4)
Departure4

In [ ]:
Source4 = []
sr4 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr4:
    s4 = data.text.split('\n')[1]
    Source4.append(s4)
Source4

In [ ]:
Destination4 = []
dn4 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn4:
    ds4 = data.text.split('\n')[-1]
    Destination4.append(ds4)
Destination4

In [ ]:
Duration4 = []
dr4 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr4:
    d4 = data.text
    Duration4.append(d4)
Duration4

In [ ]:
Stops4 = []
st4 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st4:
    s4 = data.text.split('\n')[1]
    Stops4.append(s4)
Stops4

In [ ]:
Meals4 = []
ms4 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms4:
    m4 = data.text
    Meals4.append(m4)
Meals4

In [ ]:
Price4 = []
pr4 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr4:
    p4 = data.text
    Price4.append(p4)
Price4

In [ ]:
yt4 = {'Company_Name': Company_Name4,'Flight_Name':Flight_Name4,'Arrival':Arrival4,'Departure':Departure4,'Source':Source4,'Destination':Destination4,'Duration':Duration4,'Stops': Stops4,'Meals_Avilablity':Meals4,'Price':Price4}
df5 = pd.DataFrame.from_dict(yt4,orient = 'index')
df5 = df5.transpose()
df5

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=HYD&destinationCountry=IN&flexi=0&flight_depart_date=24%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=1311164727689&version=1.3&viewName=normal'
driver.get(url)

In [ ]:
Company_Name5 = []
jt5 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt5:
    j5 =data.text
    Company_Name5.append(j5)
Company_Name5

In [ ]:
Flight_Name5 = []
fn5 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn5:
    f5 = data.text
    Flight_Name5.append(f5)
Flight_Name5

In [ ]:
Arrival5 = []
ar5 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar5:
    a5 = data.text
    Arrival5.append(a5)
Arrival5

In [ ]:
Departure5 = []
dr5 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr5:
    d5 = data.text.split('\n')[2]
    Departure5.append(d5)
Departure5

In [ ]:
Source5 = []
sr5 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr5:
    s5 = data.text.split('\n')[1]
    Source5.append(s5)
Source5

In [ ]:
Destination5 = []
dn5 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn5:
    ds5 = data.text.split('\n')[-1]
    Destination5.append(ds5)
Destination5

In [ ]:
Duration5 = []
dr5 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr5:
    d5 = data.text
    Duration5.append(d5)
Duration5

In [ ]:
Stops5 = []
st5 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st5:
    s5 = data.text.split('\n')[1]
    Stops5.append(s5)
Stops5

In [ ]:
Meals5 = []
ms5 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms5:
    m5 = data.text
    Meals5.append(m5)
Meals5

In [ ]:
Price5 = []
pr5 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr5:
    p5 = data.text
    Price5.append(p5)
Price5

In [ ]:
yt5 = {'Company_Name': Company_Name5,'Flight_Name':Flight_Name5,'Arrival':Arrival5,'Departure':Departure5,'Source':Source5,'Destination':Destination5,'Duration':Duration5,'Stops': Stops5,'Meals_Avilablity':Meals5,'Price':Price5}
df6 = pd.DataFrame.from_dict(yt5,orient = 'index')
df6 = df6.transpose()
df6

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=24%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=1512449233896&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name6 = []
jt6 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt6:
    j6 =data.text
    Company_Name6.append(j6)
Company_Name6

In [ ]:
Flight_Name6 = []
fn6 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn6:
    f6 = data.text
    Flight_Name6.append(f6)
Flight_Name6

In [ ]:
Arrival6 = []
ar6 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar6:
    a6 = data.text
    Arrival6.append(a6)
Arrival6

In [ ]:
Departure6 = []
dr6 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr6:
    d6 = data.text.split('\n')[2]
    Departure6.append(d6)
Departure6

In [ ]:
Source6 = []
sr6 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr6:
    s6 = data.text.split('\n')[1]
    Source6.append(s6)
Source6

In [ ]:
Destination6 = []
dn6 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn6:
    ds6 = data.text.split('\n')[-1]
    Destination6.append(ds6)
Destination6

In [ ]:
Duration6 = []
dr6 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr6:
    d6 = data.text
    Duration6.append(d6)
Duration6

In [ ]:
Stops6 = []
st6 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st6:
    s6 = data.text.split('\n')[1]
    Stops6.append(s6)
Stops6

In [ ]:
Meals6 = []
ms6 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms6:
    m6 = data.text
    Meals6.append(m6)
Meals6

In [ ]:
Price6 = []
pr6 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr6:
    p6 = data.text
    Price6.append(p6)
Price6

In [ ]:
yt6 = {'Company_Name': Company_Name6,'Flight_Name':Flight_Name6,'Arrival':Arrival6,'Departure':Departure6,'Source':Source6,'Destination':Destination6,'Duration':Duration6,'Stops': Stops6,'Meals_Avilablity':Meals6,'Price':Price6}
df7 = pd.DataFrame.from_dict(yt6,orient = 'index')
df7 = df7.transpose()
df7

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=24%2F03%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=527412757730&version=1.3&viewName=normal'
driver.get(url)

In [ ]:
Company_Name7 = []
jt7 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt7:
    j7 =data.text
    Company_Name7.append(j7)
Company_Name7

In [ ]:
Flight_Name7 = []
fn7 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn7:
    f7 = data.text
    Flight_Name7.append(f7)
Flight_Name7

In [ ]:
Arrival7 = []
ar7 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar7:
    a7 = data.text
    Arrival7.append(a7)
Arrival7

In [ ]:
Departure7 = []
dr7 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr7:
    d7 = data.text.split('\n')[2]
    Departure7.append(d7)
Departure7

In [ ]:
Source7 = []
sr7 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr7:
    s7 = data.text.split('\n')[1]
    Source7.append(s7)
Source7

In [ ]:
Destination7 = []
dn7 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn7:
    ds7 = data.text.split('\n')[-1]
    Destination7.append(ds7)
Destination7

In [ ]:
Duration7 = []
dr7 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr7:
    d7 = data.text
    Duration7.append(d7)
Duration7

In [ ]:
Stops7 = []
st7 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st7:
    s7 = data.text.split('\n')[1]
    Stops7.append(s7)
Stops7

In [ ]:
Meals7 = []
ms7 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms7:
    m7 = data.text
    Meals7.append(m7)
Meals7

In [ ]:
Price7 = []
pr7 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr7:
    p7 = data.text
    Price7.append(p7)
Price7

In [ ]:
yt7 = {'Company_Name': Company_Name7,'Flight_Name':Flight_Name7,'Arrival':Arrival7,'Departure':Departure7,'Source':Source7,'Destination':Destination7,'Duration':Duration7,'Stops': Stops7,'Meals_Avilablity':Meals7,'Price':Price7}
df8 = pd.DataFrame.from_dict(yt7,orient = 'index')
df8 = df8.transpose()
df8

In [ ]:
d = pd.concat([df5,df6,df7,df8])
d

In [ ]:
d.to_csv("E:\Data set\Flightprice2.csv")

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=IDR&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=175977018756&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name8 = []
jt8 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt8:
    j8 =data.text
    Company_Name8.append(j8)
Company_Name8

In [ ]:
Flight_Name8 = []
fn8 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn8:
    f8 = data.text
    Flight_Name8.append(f8)
Flight_Name8

In [ ]:
Arrival8 = []
ar8 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar8:
    a8 = data.text
    Arrival8.append(a8)
Arrival8

In [ ]:
Departure8 = []
dr8 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr8:
    d8 = data.text.split('\n')[2]
    Departure8.append(d8)
Departure8

In [ ]:
Source8 = []
sr8 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr8:
    s8 = data.text.split('\n')[1]
    Source8.append(s8)
Source8

In [ ]:
Destination8 = []
dn8 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn8:
    ds8 = data.text.split('\n')[-1]
    Destination8.append(ds8)
Destination8

In [ ]:
Duration8 = []
dr8 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr8:
    d8 = data.text
    Duration8.append(d8)
Duration8

In [ ]:
Stops8 = []
st8 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st8:
    s8 = data.text.split('\n')[1]
    Stops8.append(s8)
Stops8

In [ ]:
Meals8 = []
ms8 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms8:
    m8 = data.text
    Meals8.append(m8)
Meals8

In [ ]:
Price8 = []
pr8 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr8:
    p8 = data.text
    Price8.append(p8)
Price8

In [ ]:
yt8 = {'Company_Name': Company_Name8,'Flight_Name':Flight_Name8,'Arrival':Arrival8,'Departure':Departure8,'Source':Source8,'Destination':Destination8,'Duration':Duration8,'Stops': Stops8,'Meals_Avilablity':Meals8,'Price':Price8}
df9 = pd.DataFrame.from_dict(yt8,orient = 'index')
df9 = df9.transpose()
df9

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=MAA&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=IDR&originCountry=IN&type=O&unique=1587204204540&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name9 = []
jt9 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt9:
    j9 =data.text
    Company_Name9.append(j9)
Company_Name9

In [ ]:
Flight_Name9 = []
fn9 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn9:
    f9 = data.text
    Flight_Name9.append(f9)
Flight_Name9

In [ ]:
Arrival9 = []
ar9 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar9:
    a9 = data.text
    Arrival9.append(a9)
Arrival9

In [ ]:
Departure9 = []
dr9 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr9:
    d9 = data.text.split('\n')[2]
    Departure9.append(d9)
Departure9

In [ ]:
Source9 = []
sr9 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr9:
    s9 = data.text.split('\n')[1]
    Source9.append(s9)
Source9

In [ ]:
Destination9 = []
dn9 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn9:
    ds9 = data.text.split('\n')[-1]
    Destination9.append(ds9)
Destination9

In [ ]:
Duration9 = []
dr9 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr9:
    d9 = data.text
    Duration9.append(d9)
Duration9

In [ ]:
Stops9 = []
st9 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st9:
    s9 = data.text.split('\n')[1]
    Stops9.append(s9)
Stops9

In [ ]:
Meals9 = []
ms9 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms9:
    m9 = data.text
    Meals9.append(m9)
Meals9

In [ ]:
Price9 = []
pr9 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr9:
    p9 = data.text
    Price9.append(p9)
Price9

In [ ]:
yt9 = {'Company_Name': Company_Name9,'Flight_Name':Flight_Name9,'Arrival':Arrival9,'Departure':Departure9,'Source':Source9,'Destination':Destination9,'Duration':Duration9,'Stops': Stops9,'Meals_Avilablity':Meals9,'Price':Price9}
df10 = pd.DataFrame.from_dict(yt8,orient = 'index')
df10 = df10.transpose()
df10

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=GOI&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=MAA&originCountry=IN&type=O&unique=948282890912&version=1.1&viewName=normal'
driver.get(url)

In [ ]:
Company_Name10 = []
jt10 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt10:
    j10 =data.text
    Company_Name10.append(j10)
Company_Name10

In [ ]:
Flight_Name10 = []
fn10 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn10:
    f10 = data.text
    Flight_Name10.append(f10)
Flight_Name10

In [ ]:
Arrival10 = []
ar10 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar10:
    a10 = data.text
    Arrival10.append(a10)
Arrival10

In [ ]:
Departure10 = []
dr10 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr10:
    d10 = data.text.split('\n')[2]
    Departure10.append(d10)
Departure10

In [ ]:
Source10 = []
sr10 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr10:
    s10 = data.text.split('\n')[1]
    Source10.append(s10)
Source10

In [ ]:
Destination10 = []
dn10 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn10:
    ds10 = data.text.split('\n')[-1]
    Destination10.append(ds10)
Destination10

In [ ]:
Duration10 = []
dr10 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr10:
    d10 = data.text
    Duration10.append(d10)
Duration10

In [ ]:
Stops10 = []
st10 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st10:
    s10 = data.text.split('\n')[1]
    Stops10.append(s10)
Stops10

In [ ]:
Meals10 = []
ms10 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms10:
    m10 = data.text
    Meals10.append(m10)
Meals10

In [ ]:
Price10 = []
pr10 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr10:
    p10 = data.text
    Price10.append(p10)
Price10

In [ ]:
yt10 = {'Company_Name': Company_Name10,'Flight_Name':Flight_Name10,'Arrival':Arrival10,'Departure':Departure10,'Source':Source10,'Destination':Destination10,'Duration':Duration10,'Stops': Stops10,'Meals_Avilablity':Meals10,'Price':Price10}
df11 = pd.DataFrame.from_dict(yt8,orient = 'index')
df11 = df11.transpose()
df11

In [ ]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=GOI&destinationCountry=IN&flexi=0&flight_depart_date=26%2F03%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1597615000397&viewName=normal'
driver.get(url)

In [ ]:
Company_Name11 = []
jt11 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt11:
    j11 =data.text
    Company_Name11.append(j11)
Company_Name11

In [ ]:
Flight_Name11 = []
fn11 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn11:
    f11 = data.text
    Flight_Name11.append(f11)
Flight_Name11

In [ ]:
Arrival11 = []
ar11 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar11:
    a11 = data.text
    Arrival11.append(a11)
Arrival11

In [ ]:
Departure11 = []
dr11 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr11:
    d11 = data.text.split('\n')[2]
    Departure11.append(d11)
Departure11

In [ ]:
Source11 = []
sr11 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr11:
    s11 = data.text.split('\n')[1]
    Source11.append(s11)
Source11

In [ ]:
Destination11 = []
dn11 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn11:
    ds11 = data.text.split('\n')[-1]
    Destination11.append(ds11)
Destination11

In [ ]:
Duration11 = []
dr11 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr11:
    d11 = data.text
    Duration11.append(d11)
Duration11

In [ ]:
Stops11 = []
st11 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st11:
    s11 = data.text.split('\n')[1]
    Stops11.append(s11)
Stops11

In [ ]:
Meals11 = []
ms11 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms11:
    m11 = data.text
    Meals11.append(m11)
Meals11

In [ ]:
Price11 = []
pr11 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr11:
    p11 = data.text
    Price11.append(p11)
Price11

In [ ]:
yt11 = {'Company_Name': Company_Name11,'Flight_Name':Flight_Name11,'Arrival':Arrival11,'Departure':Departure11,'Source':Source11,'Destination':Destination11,'Duration':Duration11,'Stops': Stops11,'Meals_Avilablity':Meals11,'Price':Price11}
df12 = pd.DataFrame.from_dict(yt8,orient = 'index')
df12 = df12.transpose()
df12

In [ ]:
f = pd.concat([df9,df10,df11,df12])
f

In [ ]:
f.to_csv("E:\Data set\Flightprice3.csv")

In [7]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=GOI&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=519322347958&version=1.1&viewName=normal'
driver.get(url)

In [8]:
Company_Name12 = []
jt12 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt12:
    j12 =data.text
    Company_Name12.append(j12)
Company_Name12

['IndiGo',
 'IndiGo',
 'SpiceJet',
 'Air Asia',
 'IndiGo',
 'Vistara',
 'Go First',
 'Air India',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Go First',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Go First',
 'IndiGo',
 'Air Asia',
 'Go First',
 'IndiGo',
 'Go First',
 'Go First',
 'IndiGo',
 'Go First',
 'Air Asia',
 'Air Asia',
 'Go First',
 'Go First',
 'Go First',
 'SpiceJet',
 'Go First',
 'Go First',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'SpiceJet',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Air India',
 'SpiceJet',
 'IndiGo',
 'SpiceJet',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'SpiceJet',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air Asia',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'IndiGo',
 'Air India',
 'Go First',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Go First',
 'IndiGo',
 'Air India',
 'Go First',
 'Vistara',
 'SpiceJet',
 'Go First',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'IndiGo',
 'Go First',
 'IndiGo',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara']

In [9]:
Flight_Name12 = []
fn12 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn12:
    f12 = data.text
    Flight_Name12.append(f12)
Flight_Name12

['6E-2117',
 '6E-2792',
 'SG-8411',
 'I5-773',
 '6E-505',
 'UK-855',
 'G8-194',
 'AI-883',
 'I5-753',
 '6E-6823/6433',
 '6E-2005/367',
 'G8-323/384',
 'I5-1529/1453',
 '6E-2282/6809',
 '6E-153/6954',
 '6E-2004/793',
 'G8-338/382',
 '6E-2774/831',
 'I5-740/1453',
 'G8-530/331',
 '6E-2774/367',
 'G8-338/371',
 'G8-354/575',
 '6E-6939/6954',
 'G8-392/384',
 'I5-1732/818',
 'I5-753/679',
 'G8-328/575',
 'G8-422/813',
 'G8-336/384',
 'SG-162/4001',
 'G8-346/575',
 'G8-530/382',
 'SG-8157/455',
 'SG-191/324',
 'SG-8169/455',
 'SG-8709/455',
 'SG-534/324',
 'SG-162/3736',
 '6E-2187/309',
 '6E-2331/831',
 '6E-2187/6433',
 'SG-957',
 'I5-779',
 'I5-798',
 '6E-2325/743',
 '6E-6126/419',
 'AI-885',
 'SG-8171',
 '6E-5161',
 'SG-3755/3704',
 'I5-552',
 '6E-2144',
 '6E-2138/399',
 '6E-5318/977',
 '6E-2519/128',
 '6E-864/977',
 '6E-5342/399',
 'AI-605/685',
 'AI-805/685',
 'AI-624/685',
 'AI-605/683',
 'AI-805/683',
 'AI-624/683',
 '6E-2017/977',
 'SG-3701/3704',
 '6E-5024',
 'AI-605/663',
 'AI-805/663',
 'AI-624/663',
 '6E-5036/194',
 'I5-1529/972',
 'I5-740/972',
 'I5-1529/1983',
 'I5-740/1983',
 'AI-863/683',
 'AI-863/685',
 '6E-308/6345',
 '6E-5009/6345',
 'AI-863/663',
 'AI-636/683',
 'I5-747/818',
 'SG-8169/488',
 'SG-8709/488',
 'SG-8701/455',
 'UK-807/867',
 '6E-2143/6876',
 'AI-479/650/683',
 'G8-334/371',
 '6E-2487/806',
 'UK-801/867',
 'UK-809/867',
 'G8-286',
 '6E-5088/588',
 'AI-479/650/663',
 'G8-334/382',
 'UK-811/867',
 'SG-8157/488',
 'G8-2501/331',
 '6E-6278/711',
 'UK-859/898/867',
 'UK-859/894/867',
 'UK-941/841',
 'UK-933/841',
 'UK-993/841',
 'UK-945/841',
 'UK-847',
 'UK-815/867',
 'UK-813/867',
 'UK-817/867',
 '6E-2075/711',
 'UK-871/898/867',
 'UK-899/898/867',
 'UK-899/894/867',
 'UK-981/841',
 'UK-953/841',
 'UK-985/841',
 'UK-951/841',
 '6E-2043/5028',
 'AI-665/663',
 'UK-879/898/867',
 'UK-977/841',
 'UK-955/841',
 'UK-995/841',
 'UK-927/841',
 'SG-8701/488',
 '6E-5023/179',
 'G8-334/331',
 '6E-2075/179',
 'SG-8938/525',
 'UK-975/841',
 'UK-943/841',
 'UK-819/867']

In [10]:
Arrival12 = []
ar12 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar12:
    a12 = data.text
    Arrival12.append(a12)
Arrival12

['16:15',
 '19:00',
 '19:55',
 '20:00',
 '21:45',
 '18:40',
 '20:30',
 '22:00',
 '13:00',
 '18:00',
 '09:55',
 '18:40',
 '09:35',
 '12:45',
 '19:35',
 '12:15',
 '10:55',
 '07:55',
 '08:10',
 '06:00',
 '07:55',
 '10:55',
 '22:45',
 '17:20',
 '15:45',
 '21:40',
 '13:00',
 '20:50',
 '20:55',
 '14:00',
 '21:55',
 '19:50',
 '06:00',
 '06:20',
 '06:05',
 '19:45',
 '18:55',
 '21:25',
 '21:55',
 '15:00',
 '06:40',
 '15:00',
 '14:55',
 '05:10',
 '12:40',
 '01:50',
 '11:15',
 '10:45',
 '11:55',
 '12:15',
 '17:35',
 '10:40',
 '10:00',
 '11:55',
 '17:00',
 '23:35',
 '16:15',
 '10:45',
 '21:15',
 '20:00',
 '19:00',
 '21:15',
 '20:00',
 '19:00',
 '18:10',
 '05:45',
 '11:00',
 '21:15',
 '20:00',
 '19:00',
 '02:25',
 '09:35',
 '08:10',
 '09:35',
 '08:10',
 '14:00',
 '14:00',
 '08:20',
 '06:55',
 '14:00',
 '15:05',
 '18:45',
 '19:45',
 '18:55',
 '07:20',
 '20:40',
 '17:55',
 '21:15',
 '07:00',
 '17:25',
 '09:05',
 '19:50',
 '10:40',
 '13:00',
 '21:15',
 '07:00',
 '06:15',
 '06:20',
 '02:40',
 '08:45',
 '10:25',
 '10:25',
 '16:45',
 '15:30',
 '12:50',
 '11:40',
 '11:10',
 '08:05',
 '17:35',
 '16:05',
 '08:00',
 '20:35',
 '14:45',
 '14:45',
 '21:55',
 '20:40',
 '19:50',
 '14:20',
 '12:55',
 '08:00',
 '17:35',
 '18:55',
 '17:45',
 '10:20',
 '09:30',
 '07:20',
 '06:30',
 '07:00',
 '08:00',
 '17:05',
 '06:00',
 '07:30',
 '14:15']

In [11]:
Departure12 = []
dr12 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr12:
    d12 = data.text.split('\n')[2]
    Departure12.append(d12)
Departure12

['18:40',
 '21:30',
 '22:30',
 '22:35',
 '00:20',
 '21:20',
 '23:10',
 '00:40',
 '17:15',
 '22:35',
 '14:45',
 '23:35',
 '14:45',
 '18:00',
 '00:50',
 '17:35',
 '16:40',
 '14:00',
 '14:45',
 '12:45',
 '14:45',
 '17:55',
 '06:10',
 '00:50',
 '23:35',
 '05:55',
 '22:00',
 '06:10',
 '06:15',
 '23:35',
 '07:45',
 '06:10',
 '16:40',
 '17:05',
 '20:35',
 '17:05',
 '17:05',
 '20:35',
 '21:45',
 '21:30',
 '14:00',
 '22:35',
 '17:40',
 '07:50',
 '15:25',
 '06:50',
 '16:40',
 '13:35',
 '14:25',
 '14:50',
 '18:35',
 '13:20',
 '12:30',
 '18:10',
 '23:20',
 '06:15',
 '23:20',
 '18:10',
 '06:20',
 '06:20',
 '06:20',
 '22:20',
 '22:20',
 '22:20',
 '23:20',
 '18:35',
 '13:25',
 '14:35',
 '14:35',
 '14:35',
 '07:45',
 '18:00',
 '18:00',
 '19:25',
 '19:25',
 '22:20',
 '06:20',
 '14:10',
 '14:10',
 '14:35',
 '22:20',
 '05:55',
 '12:55',
 '12:55',
 '17:05',
 '14:05',
 '01:10',
 '22:20',
 '17:55',
 '22:40',
 '14:05',
 '14:05',
 '13:20',
 '20:35',
 '14:35',
 '16:40',
 '14:05',
 '12:55',
 '12:45',
 '15:15',
 '14:05',
 '14:05',
 '12:45',
 '12:45',
 '12:45',
 '12:45',
 '13:50',
 '14:05',
 '14:05',
 '14:05',
 '15:15',
 '14:05',
 '14:05',
 '14:05',
 '12:45',
 '12:45',
 '12:45',
 '12:45',
 '19:20',
 '14:35',
 '14:05',
 '12:45',
 '12:45',
 '12:45',
 '12:45',
 '12:55',
 '12:40',
 '12:45',
 '12:40',
 '13:10',
 '12:45',
 '12:45',
 '14:05']

In [13]:
Source12 = []
sr12 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr12:
    s12 = data.text.split('\n')[1]
    Source12.append(s12)
Source12

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [14]:
Destination12 = []
dn12 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn12:
    ds12 = data.text.split('\n')[-1]
    Destination12.append(ds12)
Destination12

['Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa']

In [15]:
Duration12 = []
dr12 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr12:
    d12 = data.text
    Duration12.append(d12)
Duration12

['2h 25m',
 '2h 30m',
 '2h 35m',
 '2h 35m',
 '2h 35m',
 '2h 40m',
 '2h 40m',
 '2h 40m',
 '4h 15m',
 '4h 35m',
 '4h 50m',
 '4h 55m',
 '5h 10m',
 '5h 15m',
 '5h 15m',
 '5h 20m',
 '5h 45m',
 '6h 05m',
 '6h 35m',
 '6h 45m',
 '6h 50m',
 '7h 00m',
 '7h 25m',
 '7h 30m',
 '7h 50m',
 '8h 15m',
 '9h 00m',
 '9h 20m',
 '9h 20m',
 '9h 35m',
 '9h 50m',
 '10h 20m',
 '10h 40m',
 '10h 45m',
 '14h 30m',
 '21h 20m',
 '22h 10m',
 '23h 10m',
 '23h 50m',
 '6h 30m',
 '7h 20m',
 '7h 35m',
 '2h 45m',
 '2h 40m',
 '2h 45m',
 '5h 00m',
 '5h 25m',
 '2h 50m',
 '2h 30m',
 '2h 35m',
 '25h 00m',
 '2h 40m',
 '2h 30m',
 '6h 15m',
 '6h 20m',
 '6h 40m',
 '7h 05m',
 '7h 25m',
 '9h 05m',
 '10h 20m',
 '11h 20m',
 '25h 05m',
 '26h 20m',
 '27h 20m',
 '5h 10m',
 '12h 50m',
 '2h 25m',
 '17h 20m',
 '18h 35m',
 '19h 35m',
 '5h 20m',
 '8h 25m',
 '9h 50m',
 '9h 50m',
 '11h 15m',
 '8h 20m',
 '16h 20m',
 '5h 50m',
 '7h 15m',
 '24h 35m',
 '7h 15m',
 '11h 10m',
 '17h 10m',
 '18h 00m',
 '9h 45m',
 '17h 25m',
 '7h 15m',
 '25h 05m',
 '10h 55m',
 '5h 15m',
 '5h 00m',
 '18h 15m',
 '2h 40m',
 '7h 35m',
 '17h 20m',
 '9h 40m',
 '7h 50m',
 '6h 35m',
 '10h 05m',
 '6h 30m',
 '27h 40m',
 '27h 40m',
 '20h 00m',
 '21h 15m',
 '23h 55m',
 '25h 05m',
 '2h 40m',
 '6h 00m',
 '20h 30m',
 '22h 00m',
 '7h 15m',
 '17h 30m',
 '23h 20m',
 '23h 20m',
 '14h 50m',
 '16h 05m',
 '16h 55m',
 '22h 25m',
 '6h 25m',
 '6h 35m',
 '20h 30m',
 '17h 50m',
 '19h 00m',
 '26h 25m',
 '27h 15m',
 '5h 35m',
 '6h 10m',
 '5h 45m',
 '4h 40m',
 '20h 05m',
 '6h 45m',
 '5h 15m',
 '23h 50m']

In [16]:
Stops12 = []
st12 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st12:
    s12 = data.text.split('\n')[1]
    Stops12.append(s12)
Stops12

['Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [20]:
Meals12 = []
ms12 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms12:
    m12 = data.text
    Meals12.append(m12)
Meals12

['Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal']

In [18]:
Price12 = []
pr12 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr12:
    p12 = data.text
    Price12.append(p12)
Price12

['8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,769',
 '8,769',
 '8,769',
 '8,790',
 '8,896',
 '8,896',
 '9,378',
 '9,987',
 '10,050',
 '10,260',
 '10,313',
 '10,421',
 '11,626',
 '11,888',
 '11,940',
 '11,940',
 '11,940',
 '11,940',
 '11,940',
 '12,045',
 '12,045',
 '12,045',
 '12,045',
 '12,045',
 '12,045',
 '12,203',
 '12,205',
 '12,308',
 '12,360',
 '12,360',
 '12,360',
 '12,780',
 '12,807',
 '12,807',
 '12,807',
 '12,807',
 '12,885',
 '12,885',
 '13,200',
 '13,200',
 '13,200',
 '13,305',
 '13,462',
 '13,697',
 '13,697',
 '13,811',
 '13,935',
 '14,513',
 '14,528',
 '14,586',
 '14,670',
 '14,775',
 '14,775',
 '15,029',
 '15,090',
 '15,106',
 '15,320',
 '15,825',
 '16,007',
 '16,108',
 '16,613',
 '16,643',
 '16,643',
 '16,718',
 '16,718',
 '16,718',
 '16,718',
 '16,770',
 '16,770',
 '16,770',
 '16,770',
 '16,823',
 '17,168',
 '17,168',
 '17,168',
 '17,243',
 '17,243',
 '17,243',
 '17,243',
 '17,348',
 '17,505',
 '17,693',
 '17,768',
 '17,768',
 '17,768',
 '17,768',
 '18,524',
 '18,765',
 '18,786',
 '19,448',
 '19,815',
 '20,445',
 '22,519',
 '22,545']

In [21]:
yt12 = {'Company_Name': Company_Name12,'Flight_Name':Flight_Name12,'Arrival':Arrival12,'Departure':Departure12,'Source':Source12,'Destination':Destination12,'Duration':Duration12,'Stops': Stops12,'Meals_Avilablity':Meals12,'Price':Price12}
df13 = pd.DataFrame.from_dict(yt12,orient = 'index')
df13 = df13.transpose()
df13

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,IndiGo,6E-2117,16:15,18:40,New Delhi,Goa,2h 25m,Non Stop,Paid Meal,"8,160"
1,IndiGo,6E-2792,19:00,21:30,New Delhi,Goa,2h 30m,Non Stop,Paid Meal,"8,160"
2,SpiceJet,SG-8411,19:55,22:30,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
3,Air Asia,I5-773,20:00,22:35,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
4,IndiGo,6E-505,21:45,00:20,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
...,...,...,...,...,...,...,...,...,...,...
174,None,None,None,None,None,None,None,None,Paid Meal,None
175,None,None,None,None,None,None,None,None,Free Meal,None
176,None,None,None,None,None,None,None,None,Free Meal,None
177,None,None,None,None,None,None,None,None,Paid Meal,None
178,None,None,None,None,None,None,None,None,Paid Meal,None

In [22]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=DEL&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=GOI&originCountry=IN&type=O&unique=708957933189&version=1.2&viewName=normal'
driver.get(url)

In [31]:
Company_Name13 = []
jt13 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt13:
    j13 =data.text
    Company_Name13.append(j13)
Company_Name13

['IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'SpiceJet',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'IndiGo',
 'Air Asia',
 'Vistara',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'Air India',
 'SpiceJet',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air Asia',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'Air Asia',
 'Air India',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'SpiceJet',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'SpiceJet',
 'IndiGo']

In [32]:
Flight_Name13 = []
fn13 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn13:
    f13 = data.text
    Flight_Name13.append(f13)
Flight_Name13

['6E-6955/158',
 'I5-5002',
 '6E-2336',
 '6E-6811/2089',
 '6E-617/5006',
 'UK-856',
 'SG-8412',
 '6E-468/6684',
 '6E-418/649',
 '6E-468/2324',
 '6E-117/2011',
 'I5-330',
 '6E-637/2135',
 'SG-8172',
 'I5-776',
 '6E-637/2106',
 '6E-5162',
 '6E-2332',
 'AI-886',
 '6E-2119',
 'I5-1455/749',
 'UK-848',
 '6E-117/2773',
 'I5-1455/1731',
 '6E-712/2279',
 'AI-884',
 'SG-958',
 '6E-6955/6288',
 'AI-697/864',
 'AI-697/806',
 'AI-697/635',
 'AI-697/866',
 'AI-697/809',
 'AI-697/677',
 'AI-697/687',
 'AI-697/442',
 'AI-697/660',
 'SG-454/8158',
 'SG-454/8710',
 'SG-454/8152',
 'SG-454/8702',
 'UK-842/910',
 'UK-842/996',
 'UK-842/940',
 'UK-842/988',
 'UK-842/950',
 'UK-842/986',
 'UK-842/954',
 'UK-842/970',
 'UK-842/960',
 'UK-842/952',
 'UK-842/944',
 'I5-774',
 'SG-325/136',
 'SG-325/535',
 '6E-6532',
 'SG-3735/160',
 'UK-842/902',
 'UK-842/928',
 '6E-6097/2012',
 '6E-714/439',
 '6E-137/6821',
 '6E-6097/2103',
 '6E-714/2518',
 '6E-137/168',
 '6E-6097/2113',
 'AI-664/660',
 'AI-684/809',
 'AI-664/888',
 'AI-684/677',
 'AI-684/687',
 'AI-684/442',
 'AI-684/660',
 'AI-684/888',
 'SG-487/8710',
 'SG-487/8152',
 'SG-487/8702',
 '6E-6877/6431',
 'I5-974/749',
 'AI-684/866',
 'UK-842/930',
 'I5-974/766',
 '6E-813/2135',
 '6E-813/2106',
 'SG-3702/3703',
 'SG-4002/160',
 '6E-744/2511',
 '6E-381/2174',
 '6E-948/5021',
 '6E-589/6991',
 '6E-381/735',
 '6E-5029/2098',
 'I5-799',
 '6E-744/2171',
 'SG-3702/3756',
 '6E-6877/5016']

In [33]:
Arrival13 = []
ar13 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar13:
    a13 = data.text
    Arrival13.append(a13)
Arrival13

['01:20',
 '12:00',
 '22:00',
 '18:30',
 '01:35',
 '21:55',
 '23:00',
 '18:10',
 '17:15',
 '18:10',
 '02:05',
 '17:45',
 '15:15',
 '15:05',
 '13:50',
 '15:15',
 '15:25',
 '13:55',
 '14:15',
 '19:15',
 '15:15',
 '14:25',
 '02:05',
 '15:15',
 '14:45',
 '01:15',
 '18:10',
 '01:20',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '23:10',
 '13:30',
 '13:30',
 '13:30',
 '13:30',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '13:20',
 '23:05',
 '21:05',
 '21:05',
 '00:50',
 '22:05',
 '13:20',
 '13:20',
 '13:10',
 '16:30',
 '06:45',
 '13:10',
 '16:30',
 '06:45',
 '13:10',
 '15:15',
 '06:50',
 '15:15',
 '06:50',
 '06:50',
 '06:50',
 '06:50',
 '06:50',
 '17:35',
 '17:35',
 '17:35',
 '01:40',
 '18:30',
 '06:50',
 '13:20',
 '18:30',
 '14:30',
 '14:30',
 '12:55',
 '08:05',
 '07:20',
 '14:40',
 '02:25',
 '21:05',
 '14:40',
 '19:50',
 '16:35',
 '07:20',
 '12:55',
 '01:40']

In [34]:
Departure13 = []
dr13 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr13:
    d13 = data.text.split('\n')[2]
    Departure13.append(d13)
Departure13

['05:50',
 '14:25',
 '00:35',
 '00:25',
 '09:20',
 '00:40',
 '01:25',
 '23:30',
 '23:20',
 '00:45',
 '09:15',
 '21:45',
 '20:00',
 '17:45',
 '16:30',
 '22:20',
 '18:00',
 '16:35',
 '16:45',
 '22:00',
 '01:05',
 '17:05',
 '07:15',
 '21:10',
 '21:15',
 '03:55',
 '21:00',
 '07:40',
 '09:05',
 '10:15',
 '11:10',
 '11:20',
 '12:20',
 '15:15',
 '18:20',
 '19:10',
 '20:10',
 '21:55',
 '00:05',
 '09:35',
 '12:30',
 '19:45',
 '20:40',
 '21:55',
 '23:00',
 '00:10',
 '00:55',
 '08:05',
 '11:00',
 '14:05',
 '14:30',
 '16:55',
 '01:50',
 '08:35',
 '23:45',
 '03:25',
 '08:40',
 '18:05',
 '08:35',
 '18:10',
 '21:40',
 '12:20',
 '19:25',
 '22:55',
 '14:10',
 '20:45',
 '20:10',
 '12:20',
 '21:15',
 '15:15',
 '18:20',
 '19:10',
 '20:10',
 '21:15',
 '00:05',
 '09:35',
 '12:30',
 '06:55',
 '01:05',
 '11:20',
 '09:40',
 '01:10',
 '20:00',
 '22:20',
 '10:25',
 '08:40',
 '12:10',
 '20:45',
 '08:45',
 '03:30',
 '22:00',
 '01:45',
 '19:20',
 '13:55',
 '22:15',
 '09:45']

In [35]:
Source13 = []
sr13 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr13:
    s13 = data.text.split('\n')[1]
    Source13.append(s13)
Source13

['Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa',
 'Goa']

In [36]:
Destination13 = []
dn13 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn13:
    ds13 = data.text.split('\n')[-1]
    Destination13.append(ds13)
Destination13

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [37]:
Duration13 = []
dr13 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr13:
    d13 = data.text
    Duration13.append(d13)
Duration13

['4h 30m',
 '2h 25m',
 '2h 35m',
 '5h 55m',
 '7h 45m',
 '2h 45m',
 '2h 25m',
 '5h 20m',
 '6h 05m',
 '6h 35m',
 '7h 10m',
 '4h 00m',
 '4h 45m',
 '2h 40m',
 '2h 40m',
 '7h 05m',
 '2h 35m',
 '2h 40m',
 '2h 30m',
 '2h 45m',
 '9h 50m',
 '2h 40m',
 '5h 10m',
 '5h 55m',
 '6h 30m',
 '2h 40m',
 '2h 50m',
 '6h 20m',
 '9h 55m',
 '11h 05m',
 '12h 00m',
 '12h 10m',
 '13h 10m',
 '16h 05m',
 '19h 10m',
 '20h 00m',
 '21h 00m',
 '8h 25m',
 '10h 35m',
 '20h 05m',
 '23h 00m',
 '6h 25m',
 '7h 20m',
 '8h 35m',
 '9h 40m',
 '10h 50m',
 '11h 35m',
 '18h 45m',
 '21h 40m',
 '24h 45m',
 '25h 10m',
 '27h 35m',
 '2h 45m',
 '11h 30m',
 '26h 40m',
 '2h 35m',
 '10h 35m',
 '4h 45m',
 '19h 15m',
 '5h 00m',
 '5h 10m',
 '5h 35m',
 '6h 15m',
 '6h 25m',
 '7h 25m',
 '7h 35m',
 '4h 55m',
 '5h 30m',
 '6h 00m',
 '8h 25m',
 '11h 30m',
 '12h 20m',
 '13h 20m',
 '14h 25m',
 '6h 30m',
 '16h 00m',
 '18h 55m',
 '5h 15m',
 '6h 35m',
 '4h 30m',
 '20h 20m',
 '6h 40m',
 '5h 30m',
 '7h 50m',
 '21h 30m',
 '24h 35m',
 '4h 50m',
 '6h 05m',
 '6h 20m',
 '6h 25m',
 '7h 20m',
 '5h 55m',
 '2h 45m',
 '6h 35m',
 '9h 20m',
 '8h 05m']

In [38]:
Stops13 = []
st13 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st13:
    s13 = data.text.split('\n')[1]
    Stops13.append(s13)
Stops13

['1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [39]:
Meals13 = []
ms13 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms13:
    m13 = data.text
    Meals13.append(m13)
Meals13

['Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal']

In [40]:
Price13 = []
pr13 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr13:
    p13 = data.text
    Price13.append(p13)
Price13

['8,970',
 '9,621',
 '9,674',
 '10,188',
 '10,188',
 '10,252',
 '10,461',
 '10,797',
 '10,797',
 '10,797',
 '10,797',
 '10,987',
 '11,406',
 '11,721',
 '11,827',
 '12,015',
 '12,089',
 '12,089',
 '12,352',
 '13,139',
 '13,369',
 '13,507',
 '13,842',
 '14,610',
 '15,060',
 '15,082',
 '15,501',
 '15,669',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,712',
 '15,996',
 '15,996',
 '15,996',
 '15,996',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,080',
 '16,237',
 '16,354',
 '16,354',
 '16,445',
 '16,446',
 '16,605',
 '16,605',
 '16,656',
 '16,656',
 '16,656',
 '16,656',
 '16,656',
 '16,656',
 '16,656',
 '16,762',
 '16,762',
 '16,762',
 '16,762',
 '16,762',
 '16,762',
 '16,762',
 '16,762',
 '16,836',
 '16,836',
 '16,836',
 '16,919',
 '16,971',
 '16,972',
 '17,130',
 '17,312',
 '17,549',
 '17,549',
 '17,756',
 '18,126',
 '18,914',
 '19,806',
 '19,806',
 '19,806',
 '19,806',
 '20,121',
 '20,541',
 '20,646',
 '20,906',
 '25,056']

In [41]:
yt13 = {'Company_Name': Company_Name13,'Flight_Name':Flight_Name13,'Arrival':Arrival13,'Departure':Departure13,'Source':Source13,'Destination':Destination13,'Duration':Duration13,'Stops': Stops13,'Meals_Avilablity':Meals13,'Price':Price13}
df14 = pd.DataFrame.from_dict(yt13,orient = 'index')
df14 = df14.transpose()
df14

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,IndiGo,6E-6955/158,01:20,05:50,Goa,New Delhi,4h 30m,1 Stop,Paid Meal,"8,970"
1,Air Asia,I5-5002,12:00,14:25,Goa,New Delhi,2h 25m,Non Stop,Paid Meal,"9,621"
2,IndiGo,6E-2336,22:00,00:35,Goa,New Delhi,2h 35m,Non Stop,Paid Meal,"9,674"
3,IndiGo,6E-6811/2089,18:30,00:25,Goa,New Delhi,5h 55m,1 Stop,Paid Meal,"10,188"
4,IndiGo,6E-617/5006,01:35,09:20,Goa,New Delhi,7h 45m,1 Stop,Paid Meal,"10,188"
...,...,...,...,...,...,...,...,...,...,...
103,None,None,None,None,None,None,None,None,Paid Meal,None
104,None,None,None,None,None,None,None,None,Paid Meal,None
105,None,None,None,None,None,None,None,None,Paid Meal,None
106,None,None,None,None,None,None,None,None,Paid Meal,None
107,None,None,None,None,None,None,None,None,Paid Meal,None

In [42]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1025777709785&version=1.1&viewName=normal'
driver.get(url)

In [43]:
Company_Name14 = []
jt14 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt14:
    j14 =data.text
    Company_Name14.append(j14)
Company_Name14

['IndiGo',
 'IndiGo',
 'Go First',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Vistara',
 'SpiceJet',
 'Air India',
 'Vistara',
 'Go First',
 'SpiceJet',
 'IndiGo',
 'IndiGo',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'SpiceJet',
 'Go First',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'Air Asia',
 'Air India',
 'IndiGo',
 'Vistara',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Go First',
 'IndiGo',
 'Air Asia',
 'Air India',
 'Air India',
 'IndiGo',
 'Go First',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Go First',
 'Air Asia',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'SpiceJet',
 'Air India',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Go First',
 'Air India',
 'Air India',
 'SpiceJet']

In [44]:
Flight_Name14 = []
fn14 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn14:
    f14 = data.text
    Flight_Name14.append(f14)
Flight_Name14

['6E-353',
 '6E-788',
 'G8-101',
 'UK-747',
 '6E-6557',
 '6E-2082',
 'UK-707',
 '6E-912',
 '6E-2057',
 '6E-2517',
 '6E-6005',
 'I5-548',
 'UK-737',
 'SG-8251',
 'AI-762',
 'UK-727',
 'G8-105',
 'SG-8254',
 '6E-6198/7235',
 '6E-2282/6469',
 'G8-151/3178',
 'G8-392/520',
 'G8-354/511',
 'G8-171/394',
 'G8-336/520',
 'G8-2513/394',
 'G8-328/511',
 'G8-119/790',
 'SG-8263',
 'G8-422/3125',
 '6E-2485/736',
 '6E-2481/736',
 '6E-5126/736',
 '6E-2107/6469',
 'I5-1529/592',
 'I5-740/592',
 'I5-1529/992',
 'AI-764',
 '6E-307/104',
 'UK-705',
 'I5-1732/611',
 '6E-204/801',
 '6E-204/7205',
 '6E-282',
 '6E-7403/6568',
 '6E-2334/7306',
 '6E-2018/6175',
 '6E-6187/7205',
 '6E-2093/7116',
 'G8-713/532',
 '6E-2095/507',
 'I5-747/992',
 'AI-504/772',
 'AI-803/772',
 '6E-2513',
 'G8-2501/511',
 'UK-993/773',
 'UK-945/773',
 'AI-605/675',
 'AI-805/675',
 'AI-624/675',
 'UK-941/771',
 'UK-933/771',
 'UK-993/771',
 'AI-506/772',
 'UK-945/771',
 'UK-941/775',
 '6E-212/784',
 'I5-1529/1562',
 'I5-740/1562',
 '6E-2087/7306',
 'AI-441/675',
 'UK-951/773',
 'UK-981/771',
 'UK-953/771',
 'AI-863/675',
 'G8-275/394',
 'I5-747/611',
 'UK-995/775',
 'UK-927/775',
 'UK-963/775',
 'SG-8903/4128',
 'SG-8903/3230',
 'UK-871/874/775',
 'UK-859/876/771',
 'UK-871/878/773',
 'UK-871/874/773',
 'UK-859/874/775',
 'UK-859/876/775',
 'UK-859/876/773',
 'UK-859/874/773',
 'AI-540/786',
 'AI-502/772',
 'AI-537/786',
 'UK-899/876/771',
 'UK-899/876/775',
 'UK-899/874/775',
 'UK-899/876/773',
 'UK-899/874/773',
 'UK-829/878/773',
 'AI-665/675',
 'SG-8187/4128',
 'AI-863/774',
 'SG-8187/3230',
 'UK-637/652/771',
 'UK-813/866/771',
 'G8-423/3136',
 'AI-621/636/774',
 'AI-665/774',
 'SG-8152/4126']

In [55]:
Arrival14 = []
ar14 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar14:
    a14 = data.text
    Arrival14.append(a14)
Arrival14

['06:05',
 '03:00',
 '05:45',
 '06:15',
 '12:25',
 '15:20',
 '17:30',
 '17:35',
 '18:40',
 '20:00',
 '22:10',
 '04:55',
 '15:55',
 '18:15',
 '20:15',
 '20:30',
 '21:25',
 '19:30',
 '16:20',
 '12:45',
 '12:20',
 '15:45',
 '22:45',
 '18:20',
 '14:00',
 '16:45',
 '20:50',
 '20:30',
 '07:05',
 '20:55',
 '13:25',
 '12:25',
 '09:20',
 '08:10',
 '09:35',
 '08:10',
 '09:35',
 '16:45',
 '05:30',
 '07:30',
 '21:40',
 '11:55',
 '11:55',
 '09:55',
 '07:20',
 '07:55',
 '07:30',
 '15:15',
 '10:15',
 '20:05',
 '15:10',
 '18:45',
 '21:15',
 '06:10',
 '08:40',
 '02:40',
 '12:50',
 '11:40',
 '21:15',
 '20:00',
 '19:00',
 '16:45',
 '15:30',
 '12:50',
 '09:45',
 '11:40',
 '16:45',
 '13:00',
 '09:35',
 '08:10',
 '14:00',
 '17:50',
 '14:20',
 '21:55',
 '20:40',
 '14:00',
 '19:50',
 '18:45',
 '10:20',
 '09:30',
 '08:50',
 '06:30',
 '06:30',
 '20:35',
 '10:25',
 '20:35',
 '20:35',
 '10:25',
 '10:25',
 '10:25',
 '10:25',
 '20:40',
 '13:30',
 '16:15',
 '14:45',
 '14:45',
 '14:45',
 '14:45',
 '14:45',
 '07:20',
 '08:00',
 '13:05',
 '14:00',
 '13:05',
 '17:10',
 '17:35',
 '08:35',
 '13:05',
 '08:00',
 '10:20']

In [46]:
Departure14 = []
dr14 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr14:
    d14 = data.text.split('\n')[2]
    Departure14.append(d14)
Departure14

['07:50',
 '05:05',
 '07:50',
 '08:20',
 '14:30',
 '17:25',
 '19:35',
 '19:40',
 '20:45',
 '22:05',
 '00:15',
 '07:05',
 '18:05',
 '20:25',
 '22:25',
 '22:45',
 '23:40',
 '21:55',
 '21:35',
 '18:15',
 '17:55',
 '00:30',
 '08:30',
 '04:20',
 '00:30',
 '04:20',
 '08:30',
 '08:30',
 '09:05',
 '07:45',
 '17:30',
 '17:30',
 '17:30',
 '18:15',
 '20:25',
 '20:25',
 '02:05',
 '19:10',
 '11:25',
 '09:35',
 '11:15',
 '18:30',
 '22:40',
 '12:00',
 '12:30',
 '18:50',
 '13:25',
 '22:40',
 '19:25',
 '08:35',
 '22:20',
 '02:05',
 '07:45',
 '07:45',
 '10:45',
 '08:30',
 '19:55',
 '19:55',
 '08:50',
 '08:50',
 '08:50',
 '09:40',
 '09:40',
 '09:40',
 '07:45',
 '09:40',
 '16:55',
 '20:10',
 '18:05',
 '18:05',
 '18:50',
 '08:50',
 '19:55',
 '09:40',
 '09:40',
 '08:50',
 '04:20',
 '11:15',
 '16:55',
 '16:55',
 '16:55',
 '13:10',
 '18:30',
 '16:55',
 '09:40',
 '19:55',
 '19:55',
 '16:55',
 '16:55',
 '19:55',
 '19:55',
 '10:50',
 '07:45',
 '10:50',
 '09:40',
 '16:55',
 '16:55',
 '19:55',
 '19:55',
 '19:55',
 '08:50',
 '13:10',
 '23:55',
 '18:30',
 '09:40',
 '09:40',
 '18:30',
 '23:55',
 '23:55',
 '09:55']

In [47]:
Source14 = []
sr14 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr14:
    s14 = data.text.split('\n')[1]
    Source14.append(s14)
Source14

['New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi',
 'New Delhi']

In [48]:
Destination14 = []
dn14 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn14:
    ds14 = data.text.split('\n')[-1]
    Destination14.append(ds14)
Destination14

['Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata']

In [49]:
Duration14 = []
dr14 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr14:
    d14 = data.text
    Duration14.append(d14)
Duration14

['1h 45m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 05m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 10m',
 '2h 15m',
 '2h 15m',
 '2h 25m',
 '5h 15m',
 '5h 30m',
 '5h 35m',
 '8h 45m',
 '9h 45m',
 '10h 00m',
 '10h 30m',
 '11h 35m',
 '11h 40m',
 '12h 00m',
 '2h 00m',
 '10h 50m',
 '4h 05m',
 '5h 05m',
 '8h 10m',
 '10h 05m',
 '10h 50m',
 '12h 15m',
 '16h 30m',
 '2h 25m',
 '5h 55m',
 '2h 05m',
 '13h 35m',
 '6h 35m',
 '10h 45m',
 '2h 05m',
 '5h 10m',
 '10h 55m',
 '5h 55m',
 '7h 25m',
 '9h 10m',
 '12h 30m',
 '7h 10m',
 '7h 20m',
 '10h 30m',
 '25h 35m',
 '2h 05m',
 '5h 50m',
 '7h 05m',
 '8h 15m',
 '11h 35m',
 '12h 50m',
 '13h 50m',
 '16h 55m',
 '18h 10m',
 '20h 50m',
 '22h 00m',
 '22h 00m',
 '24h 10m',
 '7h 10m',
 '8h 30m',
 '9h 55m',
 '4h 50m',
 '15h 00m',
 '5h 35m',
 '11h 45m',
 '13h 00m',
 '18h 50m',
 '8h 30m',
 '16h 30m',
 '6h 35m',
 '7h 25m',
 '8h 05m',
 '6h 40m',
 '12h 00m',
 '20h 20m',
 '23h 15m',
 '23h 20m',
 '23h 20m',
 '30h 30m',
 '30h 30m',
 '33h 30m',
 '33h 30m',
 '14h 10m',
 '18h 15m',
 '18h 35m',
 '18h 55m',
 '26h 10m',
 '26h 10m',
 '29h 10m',
 '29h 10m',
 '12h 35m',
 '24h 50m',
 '24h 05m',
 '9h 55m',
 '5h 25m',
 '16h 30m',
 '16h 05m',
 '9h 55m',
 '10h 50m',
 '15h 55m',
 '23h 35m']

In [50]:
Stops14 = []
st14 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st14:
    s14 = data.text.split('\n')[1]
    Stops14.append(s14)
Stops14

['Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop']

In [52]:
Meals14 = []
ms14 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms14:
    m14 = data.text
    Meals14.append(m14)
Meals14

['Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [53]:
Price14 = []
pr14 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr14:
    p14 = data.text
    Price14.append(p14)
Price14

['7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,320',
 '7,740',
 '7,827',
 '8,160',
 '8,160',
 '8,160',
 '8,160',
 '8,370',
 '8,370',
 '8,370',
 '8,580',
 '8,580',
 '9,420',
 '9,515',
 '10,260',
 '10,260',
 '11,100',
 '11,100',
 '11,100',
 '11,940',
 '11,940',
 '11,940',
 '13,069',
 '13,148',
 '13,200',
 '14,040',
 '14,040',
 '14,460',
 '14,954',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,090',
 '15,143',
 '15,294',
 '15,294',
 '15,510',
 '15,510',
 '15,615',
 '15,615',
 '15,615',
 '15,930',
 '16,035',
 '16,113',
 '16,140',
 '16,140',
 '16,140',
 '17,671',
 '17,671',
 '17,982',
 '17,982',
 '17,982',
 '17,982',
 '17,982',
 '17,982',
 '17,982',
 '17,982',
 '18,030',
 '18,030',
 '18,030',
 '18,507',
 '18,507',
 '18,507',
 '18,507',
 '18,507',
 '20,370',
 '20,550',
 '20,654',
 '21,075',
 '21,600',
 '22,125',
 '22,638',
 '23,374',
 '25,065',
 '25,695',
 '26,516']

In [56]:
yt14 = {'Company_Name': Company_Name14,'Flight_Name':Flight_Name14,'Arrival':Arrival14,'Departure':Departure14,'Source':Source14,'Destination':Destination14,'Duration':Duration14,'Stops': Stops14,'Meals_Avilablity':Meals14,'Price':Price14}
df15 = pd.DataFrame.from_dict(yt14,orient = 'index')
df15 = df15.transpose()
df15

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,IndiGo,6E-353,06:05,07:50,New Delhi,Kolkata,1h 45m,Non Stop,Paid Meal,"7,320"
1,IndiGo,6E-788,03:00,05:05,New Delhi,Kolkata,2h 05m,Non Stop,Paid Meal,"7,320"
2,Go First,G8-101,05:45,07:50,New Delhi,Kolkata,2h 05m,Non Stop,Paid Meal,"7,320"
3,Vistara,UK-747,06:15,08:20,New Delhi,Kolkata,2h 05m,Non Stop,Free Meal,"7,320"
4,IndiGo,6E-6557,12:25,14:30,New Delhi,Kolkata,2h 05m,Non Stop,Paid Meal,"7,320"
...,...,...,...,...,...,...,...,...,...,...
171,None,None,None,None,None,None,None,None,Free Meal,None
172,None,None,None,None,None,None,None,None,Free Meal,None
173,None,None,None,None,None,None,None,None,Free Meal,None
174,None,None,None,None,None,None,None,None,Free Meal,None
175,None,None,None,None,None,None,None,None,Free Meal,None

In [59]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=BLR&originCountry=IN&type=O&unique=237498959792&version=1.1&viewName=normal'
driver.get(url)

In [60]:
Company_Name15 = []
jt15 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt15:
    j15 =data.text
    Company_Name15.append(j15)
Company_Name15

['Air Asia',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Go First',
 'SpiceJet',
 'Go First',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Go First',
 'Air Asia',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'Go First',
 'Go First',
 'Air Asia',
 'Go First',
 'Go First',
 'SpiceJet',
 'Go First',
 'Go First',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air Asia',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Air India',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Air India',
 'Air India',
 'Go First',
 'Vistara',
 'Vistara',
 'Vistara']

In [61]:
Flight_Name15 = []
fn15 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn15:
    f15 = data.text
    Flight_Name15.append(f15)
Flight_Name15

['I5-1562',
 '6E-503',
 'I5-592',
 '6E-172',
 '6E-217',
 'G8-790',
 'SG-538',
 'G8-791',
 '6E-975',
 '6E-6572',
 'I5-992',
 'I5-611',
 '6E-6366/6038',
 '6E-841/6275',
 '6E-978/7205',
 '6E-541/292',
 'I5-722/548',
 'G8-320/520',
 'I5-1576/517',
 '6E-841/923',
 'I5-1562/320',
 '6E-6825/292',
 '6E-541/986',
 'I5-749/548',
 '6E-6269/292',
 '6E-6825/986',
 'G8-241/394',
 'G8-399/511',
 'I5-1567/1562',
 'G8-118/101',
 'G8-320/511',
 'SG-3027/388',
 'G8-803/532',
 'G8-395/520',
 'AI-772',
 '6E-368/157',
 '6E-6212/292',
 '6E-6212/986',
 '6E-6212/6275',
 '6E-255/736',
 '6E-457/7179',
 'I5-1731/548',
 '6E-968/507',
 '6E-442',
 '6E-227',
 '6E-484/376',
 '6E-6067/944',
 '6E-684/6494',
 '6E-6257/376',
 '6E-855/6494',
 '6E-6491/283',
 '6E-6491/944',
 '6E-537/6907',
 '6E-537/283',
 'UK-858/775',
 'UK-866/771',
 'UK-858/773',
 'UK-850/771',
 'UK-864/771',
 'UK-854/771',
 'UK-866/775',
 'UK-850/775',
 'UK-864/775',
 'UK-866/773',
 'UK-854/775',
 'UK-850/773',
 'UK-864/773',
 'UK-854/773',
 'UK-858/771',
 '6E-886/6907',
 'UK-810/737',
 'UK-814/747',
 'UK-814/705',
 'UK-810/707',
 'UK-818/747',
 'UK-802/747',
 'UK-818/705',
 'UK-820/747',
 'UK-802/705',
 'UK-810/727',
 'UK-820/705',
 'UK-814/737',
 'UK-818/737',
 'UK-814/707',
 'UK-802/737',
 'UK-818/707',
 'UK-820/737',
 'AI-610/675',
 'AI-604/675',
 'UK-816/737',
 'UK-816/707',
 'UK-816/727',
 'I5-1426/320',
 'AI-640/675',
 '6E-806/127',
 '6E-947/127',
 'AI-804/762',
 'UK-893/876/771',
 'UK-893/874/775',
 'AI-804/764',
 'UK-846/775',
 'UK-846/773',
 'UK-852/775',
 'UK-852/773',
 'AI-503/764',
 'AI-501/762',
 'UK-808/737',
 'UK-808/707',
 'AI-501/764',
 'UK-657/707',
 'AI-503/401',
 'AI-604/774',
 'AI-640/774',
 'AI-503/767',
 'UK-852/952/737',
 'AI-505/762',
 'AI-505/764',
 'G8-1825/102',
 'UK-812/737',
 'UK-812/707',
 'UK-812/727']

In [71]:
Arrival15 = []
ar15 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar15:
    a15 = data.text
    Arrival15.append(a15)
Arrival15

['14:20',
 '12:10',
 '18:15',
 '13:40',
 '18:10',
 '06:00',
 '17:05',
 '19:50',
 '22:05',
 '15:25',
 '23:30',
 '08:10',
 '12:35',
 '14:50',
 '16:10',
 '09:25',
 '00:25',
 '17:45',
 '07:35',
 '14:50',
 '14:20',
 '08:05',
 '09:25',
 '22:30',
 '07:00',
 '08:05',
 '17:35',
 '21:30',
 '06:50',
 '20:30',
 '17:45',
 '05:45',
 '17:15',
 '08:15',
 '05:20',
 '05:15',
 '11:10',
 '11:10',
 '11:10',
 '08:35',
 '08:20',
 '17:55',
 '16:50',
 '09:15',
 '06:30',
 '07:10',
 '15:30',
 '21:45',
 '05:15',
 '20:10',
 '12:35',
 '12:35',
 '10:15',
 '10:15',
 '06:40',
 '21:40',
 '06:40',
 '19:55',
 '19:00',
 '18:25',
 '21:40',
 '19:55',
 '19:00',
 '21:40',
 '18:25',
 '19:55',
 '19:00',
 '18:25',
 '06:40',
 '08:55',
 '07:00',
 '21:10',
 '21:10',
 '07:00',
 '19:40',
 '18:50',
 '19:40',
 '17:45',
 '18:50',
 '07:00',
 '17:45',
 '21:10',
 '19:40',
 '21:10',
 '18:50',
 '19:40',
 '17:45',
 '19:10',
 '08:20',
 '11:30',
 '11:30',
 '11:30',
 '13:05',
 '06:45',
 '21:40',
 '00:25',
 '06:10',
 '19:55',
 '19:55',
 '06:10',
 '08:30',
 '08:30',
 '09:30',
 '09:30',
 '17:00',
 '13:20',
 '08:00',
 '08:00',
 '13:20',
 '11:30',
 '17:00',
 '08:20',
 '06:45',
 '17:00',
 '09:30',
 '10:00',
 '10:00',
 '06:30',
 '09:45',
 '09:45',
 '09:45']

In [63]:
Departure15 = []
dr15 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr15:
    d15 = data.text.split('\n')[2]
    Departure15.append(d15)
Departure15

['18:05',
 '14:20',
 '20:25',
 '16:05',
 '20:35',
 '08:30',
 '19:35',
 '22:20',
 '00:35',
 '18:00',
 '02:05',
 '11:15',
 '17:00',
 '19:45',
 '22:40',
 '16:00',
 '07:05',
 '00:30',
 '14:35',
 '21:50',
 '22:00',
 '16:00',
 '17:30',
 '07:05',
 '16:00',
 '17:30',
 '04:20',
 '08:30',
 '18:05',
 '07:50',
 '08:30',
 '20:50',
 '08:35',
 '00:30',
 '07:45',
 '13:25',
 '16:00',
 '17:30',
 '19:45',
 '17:30',
 '15:55',
 '07:05',
 '22:20',
 '11:50',
 '09:05',
 '13:20',
 '22:30',
 '05:15',
 '13:20',
 '05:15',
 '19:15',
 '22:30',
 '17:15',
 '19:15',
 '16:55',
 '09:40',
 '19:55',
 '09:40',
 '09:40',
 '09:40',
 '16:55',
 '16:55',
 '16:55',
 '19:55',
 '16:55',
 '19:55',
 '19:55',
 '19:55',
 '09:40',
 '17:15',
 '18:05',
 '08:20',
 '09:35',
 '19:35',
 '08:20',
 '08:20',
 '09:35',
 '08:20',
 '09:35',
 '22:45',
 '09:35',
 '18:05',
 '18:05',
 '19:35',
 '18:05',
 '19:35',
 '18:05',
 '08:50',
 '08:50',
 '18:05',
 '19:35',
 '22:45',
 '22:00',
 '08:50',
 '06:05',
 '06:05',
 '22:25',
 '09:40',
 '16:55',
 '19:10',
 '16:55',
 '19:55',
 '16:55',
 '19:55',
 '19:10',
 '22:25',
 '18:05',
 '19:35',
 '19:10',
 '19:35',
 '09:00',
 '23:55',
 '23:55',
 '14:30',
 '18:05',
 '22:25',
 '19:10',
 '13:45',
 '18:05',
 '19:35',
 '22:45']

In [64]:
Source15 = []
sr15 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr15:
    s15 = data.text.split('\n')[1]
    Source15.append(s15)
Source15

['Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore']

In [65]:
Destination15 = []
dn15 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn15:
    ds15 = data.text.split('\n')[-1]
    Destination15.append(ds15)
Destination15

['Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata']

In [66]:
Duration15 = []
dr15 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr15:
    d15 = data.text
    Duration15.append(d15)
Duration15

['3h 45m',
 '2h 10m',
 '2h 10m',
 '2h 25m',
 '2h 25m',
 '2h 30m',
 '2h 30m',
 '2h 30m',
 '2h 30m',
 '2h 35m',
 '2h 35m',
 '3h 05m',
 '4h 25m',
 '4h 55m',
 '6h 30m',
 '6h 35m',
 '6h 40m',
 '6h 45m',
 '7h 00m',
 '7h 00m',
 '7h 40m',
 '7h 55m',
 '8h 05m',
 '8h 35m',
 '9h 00m',
 '9h 25m',
 '10h 45m',
 '11h 00m',
 '11h 15m',
 '11h 20m',
 '14h 45m',
 '15h 05m',
 '15h 20m',
 '16h 15m',
 '2h 25m',
 '8h 10m',
 '4h 50m',
 '6h 20m',
 '8h 35m',
 '8h 55m',
 '7h 35m',
 '13h 10m',
 '5h 30m',
 '2h 35m',
 '2h 35m',
 '6h 10m',
 '7h 00m',
 '7h 30m',
 '8h 05m',
 '9h 05m',
 '6h 40m',
 '9h 55m',
 '7h 00m',
 '9h 00m',
 '10h 15m',
 '12h 00m',
 '13h 15m',
 '13h 45m',
 '14h 40m',
 '15h 15m',
 '19h 15m',
 '21h 00m',
 '21h 55m',
 '22h 15m',
 '22h 30m',
 '24h 00m',
 '24h 55m',
 '25h 30m',
 '27h 00m',
 '8h 20m',
 '11h 05m',
 '11h 10m',
 '12h 25m',
 '12h 35m',
 '12h 40m',
 '13h 30m',
 '13h 55m',
 '14h 35m',
 '14h 45m',
 '15h 45m',
 '15h 50m',
 '20h 55m',
 '22h 25m',
 '22h 25m',
 '23h 15m',
 '23h 55m',
 '24h 20m',
 '13h 40m',
 '24h 30m',
 '6h 35m',
 '8h 05m',
 '11h 15m',
 '8h 55m',
 '26h 05m',
 '8h 25m',
 '5h 40m',
 '16h 15m',
 '13h 45m',
 '21h 00m',
 '13h 00m',
 '8h 25m',
 '11h 25m',
 '7h 25m',
 '10h 25m',
 '26h 10m',
 '9h 05m',
 '10h 05m',
 '11h 35m',
 '5h 50m',
 '8h 05m',
 '16h 00m',
 '15h 35m',
 '17h 10m',
 '21h 30m',
 '8h 35m',
 '12h 25m',
 '9h 10m',
 '7h 15m',
 '8h 20m',
 '9h 50m',
 '13h 00m']

In [67]:
Stops15 = []
st15 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st15:
    s15 = data.text.split('\n')[1]
    Stops15.append(s15)
Stops15

['1 Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop']

In [68]:
Meals15 = []
ms15 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms15:
    m15 = data.text
    Meals15.append(m15)
Meals15

['Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal']

In [69]:
Price15 = []
pr15 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr15:
    p15 = data.text
    Price15.append(p15)
Price15

['6,096',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,333',
 '6,334',
 '6,732',
 '7,131',
 '7,131',
 '7,131',
 '7,131',
 '7,929',
 '8,644',
 '8,727',
 '8,929',
 '9,530',
 '10,901',
 '10,901',
 '10,901',
 '10,901',
 '10,901',
 '11,163',
 '11,163',
 '11,373',
 '11,373',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,097',
 '12,423',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '12,990',
 '13,474',
 '13,684',
 '13,793',
 '13,793',
 '13,793',
 '14,056',
 '14,104',
 '14,261',
 '14,313',
 '15,154',
 '15,841',
 '15,841',
 '15,994',
 '16,204',
 '16,204',
 '16,729',
 '16,729',
 '16,939',
 '17,044',
 '17,044',
 '17,044',
 '17,884',
 '18,304',
 '18,724',
 '18,829',
 '19,249',
 '19,669',
 '20,781',
 '23,449',
 '24,289',
 '25,180',
 '27,334',
 '27,334',
 '27,334']

In [72]:
yt15 = {'Company_Name': Company_Name15,'Flight_Name':Flight_Name15,'Arrival':Arrival15,'Departure':Departure15,'Source':Source15,'Destination':Destination15,'Duration':Duration15,'Stops': Stops15,'Meals_Avilablity':Meals15,'Price':Price15}
df16 = pd.DataFrame.from_dict(yt15,orient = 'index')
df16 = df16.transpose()
df16

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,Air Asia,I5-1562,14:20,18:05,Bangalore,Kolkata,3h 45m,1 Stop,Paid Meal,"6,096"
1,IndiGo,6E-503,12:10,14:20,Bangalore,Kolkata,2h 10m,Non Stop,Paid Meal,"6,333"
2,Air Asia,I5-592,18:15,20:25,Bangalore,Kolkata,2h 10m,Non Stop,Paid Meal,"6,333"
3,IndiGo,6E-172,13:40,16:05,Bangalore,Kolkata,2h 25m,Non Stop,Paid Meal,"6,333"
4,IndiGo,6E-217,18:10,20:35,Bangalore,Kolkata,2h 25m,Non Stop,Paid Meal,"6,333"
...,...,...,...,...,...,...,...,...,...,...
174,None,None,None,None,None,None,None,None,Paid Meal,None
175,None,None,None,None,None,None,None,None,Paid Meal,None
176,None,None,None,None,None,None,None,None,Paid Meal,None
177,None,None,None,None,None,None,None,None,Free Meal,None
178,None,None,None,None,None,None,None,None,Free Meal,None

In [73]:
url = 'https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=CCU&destinationCountry=IN&flexi=0&flight_depart_date=28%2F03%2F2022&hb=0&noOfSegments=1&origin=BOM&originCountry=IN&type=O&unique=871923176022&version=1.1&viewName=normal'
driver.get(url)

In [74]:
Company_Name16 = []
jt16 = driver.find_elements_by_xpath('//span[@class ="i-b text ellipsis"]')
for data in jt16:
    j16 =data.text
    Company_Name16.append(j16)
Company_Name16

['IndiGo',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'IndiGo',
 'Go First',
 'Vistara',
 'SpiceJet',
 'IndiGo',
 'SpiceJet',
 'Go First',
 'Air India',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Go First',
 'IndiGo',
 'IndiGo',
 'Air Asia',
 'Go First',
 'Go First',
 'IndiGo',
 'Go First',
 'SpiceJet',
 'IndiGo',
 'Go First',
 'Go First',
 'Go First',
 'SpiceJet',
 'Air Asia',
 'SpiceJet',
 'SpiceJet',
 'Go First',
 'Air Asia',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Go First',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Air India',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'IndiGo',
 'IndiGo',
 'Vistara',
 'Vistara',
 'Vistara',
 'Air India',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Go First',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'Air India',
 'IndiGo',
 'IndiGo',
 'Air India',
 'Air India',
 'Air Asia',
 'Air India',
 'Vistara',
 'Air India',
 'Air India',
 'Air India',
 'Vistara',
 'Vistara',
 'Vistara',
 'Vistara',
 'SpiceJet',
 'SpiceJet',
 'SpiceJet',
 'Vistara',
 'Vistara',
 'Vistara']

In [75]:
Flight_Name16 = []
fn16 = driver.find_elements_by_xpath('//p[@class ="normal fs-11 font-lightestgrey no-wrap fl-no"]')
for data in fn16:
    f16 = data.text
    Flight_Name16.append(f16)
Flight_Name16

['6E-429',
 '6E-5296',
 '6E-5289',
 'UK-773',
 '6E-395',
 'G8-511',
 'UK-771',
 'SG-241',
 '6E-822',
 'SG-467',
 'G8-520',
 'AI-675',
 'UK-775',
 '6E-6086',
 '6E-6165/7205',
 '6E-5324/669',
 '6E-6227/801',
 '6E-843/6553',
 'I5-942/592',
 'G8-330/101',
 '6E-5232/7235',
 '6E-542/7117',
 'I5-338/992',
 'G8-383/791',
 'G8-345/101',
 '6E-6025/6181',
 'G8-363/532',
 'SG-8702/8251',
 '6E-6227/7205',
 'G8-322/101',
 'G8-325/790',
 'G8-341/101',
 'SG-8710/8263',
 'I5-330/548',
 'SG-252/538',
 'SG-8702/8254',
 'G8-398/790',
 'I5-942/992',
 'SG-8152/8251',
 'SG-8158/8263',
 'SG-251/623',
 'G8-339/101',
 'SG-8152/8254',
 'SG-611/388',
 'SG-8710/8251',
 'SG-8702/8263',
 'SG-8710/8254',
 'AI-774',
 '6E-6301/736',
 '6E-5315/6553',
 '6E-5388/944',
 '6E-6697/6907',
 '6E-5314/944',
 '6E-461/376',
 '6E-6697/283',
 '6E-461/6907',
 '6E-5386/6494',
 '6E-6697/944',
 'AI-607/772',
 'AI-639/772',
 'AI-603/772',
 '6E-192/6494',
 'UK-910/727',
 'UK-952/737',
 'UK-952/707',
 'UK-986/747',
 'UK-952/727',
 'UK-950/747',
 'UK-986/705',
 'UK-988/747',
 'UK-950/705',
 'UK-940/747',
 'UK-988/705',
 'UK-940/705',
 '6E-5232/7116',
 '6E-5349/507',
 'UK-960/737',
 'UK-902/727',
 'UK-960/707',
 'AI-633/482/762',
 'G8-339/105',
 'G8-391/105',
 'G8-321/105',
 'G8-319/105',
 'G8-327/105',
 'AI-687/762',
 'AI-442/762',
 'AI-677/762',
 'AI-809/762',
 'AI-570/786',
 'AI-866/762',
 'AI-806/762',
 'AI-864/762',
 '6E-6603/6907',
 '6E-6603/283',
 'AI-677/764',
 'AI-809/764',
 'AI-866/764',
 'AI-806/764',
 'AI-864/764',
 '6E-818/376',
 '6E-818/6907',
 'AI-671/786',
 'AI-651/470/762',
 'I5-629/992',
 'AI-677/537/786',
 'UK-994/737',
 'AI-651/470/764',
 'AI-888/401',
 'AI-660/401',
 'UK-651/707',
 'UK-877/880/707',
 'UK-621/672/727',
 'UK-653/707',
 'SG-163/4128',
 'SG-163/3230',
 'SG-397/3230',
 'UK-852/618/707',
 'UK-841/848/727',
 'UK-647/644/707']

In [76]:
Arrival16 = []
ar16 = driver.find_elements_by_xpath('//div[@class ="i-b pr"]')
for data in ar16:
    a16 = data.text
    Arrival16.append(a16)
Arrival16

['07:50',
 '09:50',
 '12:55',
 '17:20',
 '17:35',
 '05:50',
 '07:00',
 '06:10',
 '06:25',
 '20:50',
 '21:45',
 '06:00',
 '14:05',
 '19:25',
 '17:10',
 '05:20',
 '12:20',
 '15:00',
 '13:05',
 '00:10',
 '13:55',
 '15:45',
 '18:10',
 '13:00',
 '22:30',
 '21:25',
 '22:30',
 '10:15',
 '12:20',
 '21:30',
 '21:45',
 '20:40',
 '21:55',
 '19:45',
 '08:10',
 '10:15',
 '20:00',
 '13:05',
 '07:20',
 '19:35',
 '19:35',
 '18:00',
 '07:20',
 '05:40',
 '21:55',
 '10:15',
 '21:55',
 '21:05',
 '09:10',
 '10:20',
 '17:15',
 '11:10',
 '16:05',
 '06:05',
 '11:10',
 '06:05',
 '18:05',
 '11:10',
 '16:40',
 '09:30',
 '06:10',
 '19:55',
 '17:35',
 '12:25',
 '12:25',
 '22:45',
 '12:25',
 '21:55',
 '22:45',
 '20:55',
 '21:55',
 '19:45',
 '20:55',
 '19:45',
 '13:55',
 '13:15',
 '11:55',
 '15:45',
 '11:55',
 '05:45',
 '18:00',
 '14:35',
 '12:10',
 '09:55',
 '08:15',
 '16:00',
 '15:25',
 '13:00',
 '10:00',
 '05:25',
 '09:00',
 '08:00',
 '07:00',
 '09:00',
 '09:00',
 '13:00',
 '10:00',
 '09:00',
 '08:00',
 '07:00',
 '07:15',
 '07:15',
 '09:00',
 '09:50',
 '12:25',
 '13:00',
 '10:25',
 '09:50',
 '19:00',
 '18:00',
 '16:05',
 '10:45',
 '13:20',
 '06:00',
 '13:00',
 '13:00',
 '08:25',
 '12:10',
 '11:25',
 '10:25']

In [77]:
Departure16 = []
dr16 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dr16:
    d16 = data.text.split('\n')[2]
    Departure16.append(d16)
Departure16

['10:20',
 '12:25',
 '15:30',
 '19:55',
 '20:10',
 '08:30',
 '09:40',
 '08:55',
 '09:10',
 '23:35',
 '00:30',
 '08:50',
 '16:55',
 '22:20',
 '22:40',
 '11:05',
 '18:30',
 '21:40',
 '20:25',
 '07:50',
 '21:35',
 '23:40',
 '02:05',
 '22:20',
 '07:50',
 '06:50',
 '08:35',
 '20:25',
 '22:40',
 '07:50',
 '08:30',
 '07:50',
 '09:05',
 '07:05',
 '19:35',
 '21:55',
 '08:30',
 '02:05',
 '20:25',
 '09:05',
 '09:15',
 '07:50',
 '21:55',
 '20:50',
 '20:25',
 '09:05',
 '21:55',
 '23:55',
 '17:30',
 '21:40',
 '22:30',
 '17:15',
 '22:30',
 '13:20',
 '19:15',
 '17:15',
 '05:15',
 '22:30',
 '07:45',
 '07:45',
 '07:45',
 '05:15',
 '22:45',
 '18:05',
 '19:35',
 '08:20',
 '22:45',
 '08:20',
 '09:35',
 '08:20',
 '09:35',
 '08:20',
 '09:35',
 '09:35',
 '19:25',
 '22:20',
 '18:05',
 '22:45',
 '19:35',
 '22:25',
 '23:40',
 '23:40',
 '23:40',
 '23:40',
 '23:40',
 '22:25',
 '22:25',
 '22:25',
 '22:25',
 '10:50',
 '22:25',
 '22:25',
 '22:25',
 '17:15',
 '19:15',
 '19:10',
 '19:10',
 '19:10',
 '19:10',
 '19:10',
 '13:20',
 '17:15',
 '10:50',
 '22:25',
 '02:05',
 '10:50',
 '18:05',
 '19:10',
 '09:00',
 '09:00',
 '19:35',
 '19:35',
 '22:45',
 '19:35',
 '13:10',
 '18:30',
 '18:30',
 '19:35',
 '22:45',
 '19:35']

In [78]:
Source16 = []
sr16 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in sr16:
    s16 = data.text.split('\n')[1]
    Source16.append(s16)
Source16

['Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai',
 'Mumbai']

In [79]:
Destination16 = []
dn16 = driver.find_elements_by_xpath('//div[@class ="timing-det bdr-btm v-aligm-t"]')
for data in dn16:
    ds16 = data.text.split('\n')[-1]
    Destination16.append(ds16)
Destination16

['Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata',
 'Kolkata']

In [80]:
Duration16 = []
dr16 = driver.find_elements_by_xpath('//p[@class ="fs-12 bold du mb-2"]')
for data in dr16:
    d16 = data.text
    Duration16.append(d16)
Duration16

['2h 30m',
 '2h 35m',
 '2h 35m',
 '2h 35m',
 '2h 35m',
 '2h 40m',
 '2h 40m',
 '2h 45m',
 '2h 45m',
 '2h 45m',
 '2h 45m',
 '2h 50m',
 '2h 50m',
 '2h 55m',
 '5h 30m',
 '5h 45m',
 '6h 10m',
 '6h 40m',
 '7h 20m',
 '7h 40m',
 '7h 40m',
 '7h 55m',
 '7h 55m',
 '9h 20m',
 '9h 20m',
 '9h 25m',
 '10h 05m',
 '10h 10m',
 '10h 20m',
 '10h 20m',
 '10h 45m',
 '11h 10m',
 '11h 10m',
 '11h 20m',
 '11h 25m',
 '11h 40m',
 '12h 30m',
 '13h 00m',
 '13h 05m',
 '13h 30m',
 '13h 40m',
 '13h 50m',
 '14h 35m',
 '15h 10m',
 '22h 30m',
 '22h 50m',
 '24h 00m',
 '2h 50m',
 '8h 20m',
 '11h 20m',
 '5h 15m',
 '6h 05m',
 '6h 25m',
 '7h 15m',
 '8h 05m',
 '11h 10m',
 '11h 10m',
 '11h 20m',
 '15h 05m',
 '22h 15m',
 '25h 35m',
 '9h 20m',
 '5h 10m',
 '5h 40m',
 '7h 10m',
 '9h 35m',
 '10h 20m',
 '10h 25m',
 '10h 50m',
 '11h 25m',
 '11h 40m',
 '12h 35m',
 '12h 40m',
 '13h 50m',
 '5h 30m',
 '9h 05m',
 '6h 10m',
 '7h 00m',
 '7h 40m',
 '16h 40m',
 '5h 40m',
 '9h 05m',
 '11h 30m',
 '13h 45m',
 '15h 25m',
 '6h 25m',
 '7h 00m',
 '9h 25m',
 '12h 25m',
 '5h 25m',
 '13h 25m',
 '14h 25m',
 '15h 25m',
 '8h 15m',
 '10h 15m',
 '6h 10m',
 '9h 10m',
 '10h 10m',
 '11h 10m',
 '12h 10m',
 '6h 05m',
 '10h 00m',
 '25h 50m',
 '36h 35m',
 '13h 40m',
 '21h 50m',
 '7h 40m',
 '33h 20m',
 '14h 00m',
 '15h 00m',
 '27h 30m',
 '8h 50m',
 '9h 25m',
 '13h 35m',
 '24h 10m',
 '5h 30m',
 '10h 05m',
 '7h 25m',
 '11h 20m',
 '9h 10m']

In [81]:
Stops16 = []
st16 = driver.find_elements_by_xpath('//div[@class ="stop-cont pl-13"]')
for data in st16:
    s16 = data.text.split('\n')[1]
    Stops16.append(s16)
Stops16

['Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 'Non Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)',
 '1 Stop',
 '1 Stop',
 '1 Stop',
 '2 Stop(s)',
 '2 Stop(s)',
 '2 Stop(s)']

In [82]:
Meals16 = []
ms16 = driver.find_elements_by_xpath('//span[@class ="meal"]')
for data in ms16:
    m16 = data.text
    Meals16.append(m16)
Meals16

['Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Paid Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal',
 'Free Meal']

In [83]:
Price16 = []
pr16 = driver.find_elements_by_xpath('//div[@class ="i-b tipsy fare-summary-tooltip fs-18"]')
for data in pr16:
    p16 = data.text
    Price16.append(p16)
Price16

['8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,148',
 '8,673',
 '9,366',
 '9,975',
 '10,826',
 '10,826',
 '10,826',
 '10,826',
 '10,826',
 '10,826',
 '10,826',
 '10,826',
 '12,138',
 '12,138',
 '12,138',
 '12,191',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,200',
 '12,411',
 '13,020',
 '13,092',
 '13,092',
 '13,092',
 '13,381',
 '14,107',
 '14,107',
 '14,107',
 '14,107',
 '14,107',
 '14,238',
 '14,238',
 '14,238',
 '14,238',
 '14,448',
 '14,448',
 '14,448',
 '14,448',
 '14,501',
 '14,501',
 '15,078',
 '15,078',
 '15,288',
 '15,288',
 '15,288',
 '15,446',
 '15,446',
 '15,708',
 '15,839',
 '16,024',
 '16,131',
 '16,338',
 '17,225',
 '17,283',
 '17,283',
 '17,283',
 '17,660',
 '18,237',
 '19,068',
 '19,916',
 '20,860',
 '20,860',
 '21,001',
 '31,773',
 '32,143']

In [84]:
yt16 = {'Company_Name': Company_Name16,'Flight_Name':Flight_Name16,'Arrival':Arrival16,'Departure':Departure16,'Source':Source16,'Destination':Destination16,'Duration':Duration16,'Stops': Stops16,'Meals_Avilablity':Meals16,'Price':Price16}
df17 = pd.DataFrame.from_dict(yt16,orient = 'index')
df17 = df17.transpose()
df17

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,IndiGo,6E-429,07:50,10:20,Mumbai,Kolkata,2h 30m,Non Stop,Paid Meal,"8,148"
1,IndiGo,6E-5296,09:50,12:25,Mumbai,Kolkata,2h 35m,Non Stop,Paid Meal,"8,148"
2,IndiGo,6E-5289,12:55,15:30,Mumbai,Kolkata,2h 35m,Non Stop,Paid Meal,"8,148"
3,Vistara,UK-773,17:20,19:55,Mumbai,Kolkata,2h 35m,Non Stop,Free Meal,"8,148"
4,IndiGo,6E-395,17:35,20:10,Mumbai,Kolkata,2h 35m,Non Stop,Paid Meal,"8,148"
...,...,...,...,...,...,...,...,...,...,...
159,None,None,None,None,None,None,None,None,Free Meal,None
160,None,None,None,None,None,None,None,None,Free Meal,None
161,None,None,None,None,None,None,None,None,Free Meal,None
162,None,None,None,None,None,None,None,None,Free Meal,None
163,None,None,None,None,None,None,None,None,Free Meal,None

In [85]:
p = pd.concat([df13,df14,df15,df16,df17])
p

,Company_Name,Flight_Name,Arrival,Departure,Source,Destination,Duration,Stops,Meals_Avilablity,Price
0,IndiGo,6E-2117,16:15,18:40,New Delhi,Goa,2h 25m,Non Stop,Paid Meal,"8,160"
1,IndiGo,6E-2792,19:00,21:30,New Delhi,Goa,2h 30m,Non Stop,Paid Meal,"8,160"
2,SpiceJet,SG-8411,19:55,22:30,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
3,Air Asia,I5-773,20:00,22:35,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
4,IndiGo,6E-505,21:45,00:20,New Delhi,Goa,2h 35m,Non Stop,Paid Meal,"8,160"
...,...,...,...,...,...,...,...,...,...,...
159,None,None,None,None,None,None,None,None,Free Meal,None
160,None,None,None,None,None,None,None,None,Free Meal,None
161,None,None,None,None,None,None,None,None,Free Meal,None
162,None,None,None,None,None,None,None,None,Free Meal,None
163,None,None,None,None,None,None,None,None,Free Meal,None

In [87]:
p.to_csv("E:\Data set\Flightprice4.csv")